### ISSUE TITLE
typo in Spark path

### ISSUE THREAD

**Issue by mromanello** [mromanello/ph-submissions#4]
(cc @faustusdotbe)

Spark's path should be 

`/Applications/spark-x.x.x-bin-hadoop2.7/bin`

instead of 

`/Applications/spark-x.x.x-bin-hadoop2.7`

Check + fix in both EN and FR versions, then open a PR upstream.

**Comment by drvenabili** [comment]
Added to PR https://github.com/programminghistorian/ph-submissions/pull/392
